### ISSUE TITLE
Support external endpoint registration

### ISSUE THREAD

**Issue by juansalvatella** [CyCoreSystems/asterisk-k8s-demo#7]
Hi Sean, I am struggling to register an external endpoint in Asterisk as the endpoint identification method is by IP and every SIP message coming from Kamailio gets linked to the "proxies" endpoint. 

If the identification method was changed to username, then all the incoming calls from the PSTN proxied through Kamailio wouldn't find an endpoint and the solution would stop working.  Is there a way to allow this demo setup to be compatible with external endpoint registration?

I have already changed the Kamailio config to pass through all REGISTER messages to Asterisk.

**Comment by Ulexus** [comment]
This example was not intended to handle SIP registrations, no.  There are actually a number of complications if you want to, for whatever reason, pass registrations through to the Asterisk machine(s).  This would not be an appropriate base for that.

The more common approach would be to register against the kamailio proxies, passing only trusted traffic in to the Asterisk boxes.  This is also out-of-scope for this demonstration, though.

I'm happy to consult, but I do not want to implement registrations into this demo at the moment.
